site_name: Проектирование автоматизированной системы заказа и приготовления блюд в ресторане быстрого питания

repo_name: xxx996/Otus
repo_url: https://github.com/xxx996/Otus

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
    - toc.follow
    - search.highlight
    - search.suggest
    - content.code.copy
  language: ru
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Переключиться на тёмную тему
      primary: blue
      accent: violet
      background: white  # Белый фон для светлой темы
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Переключиться на светлую тему
      primary: violet
      accent: darkgreen
      background: darkgreen

extra_css:
  - stylesheets/extra.css  # Подключение дополнительного CSS-файла

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid

plugins:
  - search
  - swagger-ui-tag
  - mermaid2
  - swagger-ui-tag
  - build_plantuml:
      render: 'server' # or "local" for local rendering
      bin_path: '/usr/local/bin/plantuml' # ignored when render: server
      server: 'http://www.plantuml.com/plantuml' # official plantuml server
      disable_ssl_certificate_validation: true # for self-signed and invalid certs
      output_format: 'svg' # or "png"
      diagram_root: 'docs/diagrams' # should reside under docs_dir
      output_folder: 'out'
      input_folder: 'src'
      input_extensions: '' # comma separated list of extensions to parse, by default every file is parsed
  - enumerate-headings:
      exclude:
        - index.md
        - glossary.md
  # - print-site:
  #     path_to_pdf: "assets/test.pdf"
  - glightbox


nav:
  - Домашняя страница:
    - index.md
  - Документация:
    - info.md
    - glossary.md
    - brs.md
    - req.md
    - models.md
    - architecture.md
    - uix.md
    - api.md
  - Задачи:
    - uc.md
