openapi: 3.0.2
info:
  version: 3.0.0
  title: 'Robot and dot'
  description: 'API для заказа блюд через приложение'
  contact: 
    name: Контактная информация
    url: robot.com
    email: robotanddot@gmail.com
servers:
  # Added by API Auto Mocking Plugin
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/sanyartemov/test/3.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/cottoffeus/Dot_Eats/1
paths:
 /users/login:
  post:
    tags: [Пользователи]
    security:
      - bearerAuth: []
    summary: Аутентификация пользователя
    description: Позволяет аутентифицироваться клиенту
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Login'
    responses:  
      '200':
        description: Успешная аутентификация
        content:
         application/json:
          schema:
           type: object
           properties:
            result:
              type: string
              example: Аутентификация прошла успешно
              
      '400':
          description: Ошибка клиента
      '404':
          description: Информация недоступна
      'default':
          description: Внутренняя ошибка сервера
 /users/register:
  post:
    tags: [Пользователи]
    security:
      - bearerAuth: []
    summary: Регистрация пользователя
    description: Позволяет зарегистрироваться пользователю
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Register'
    responses:  
      '200':
        description: Успешная регистрация
        content:
         application/json:
          schema:
           type: object
           properties:
            result:
              type: string
              example: Прошла успешная регистрация
              
      '400':
          description: Ошибка клиента
      '404':
          description: Информация недоступна
      'default':
          description: Внутренняя ошибка сервера
 /recovery:
  post:
    tags: [Пользователи]
    security:
      - bearerAuth: []
    summary: Восстановление пароля
    description: Позволяет клиенту восстановить пароль
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Recovery'
    responses:  
      '200':
        description: Успешное восстановление пароля
        content:
         application/json:
          schema:
           type: object
           properties:
            result:
              type: string
              example: Пароль успешно восстановлен
              
      '400':
          description: Ошибка клиента
      '404':
          description: Информация недоступна
      'default':
          description: Внутренняя ошибка сервера
 /menu:
  get:
    tags: [Меню]
    security:
      - bearerAuth: []
    summary: Получение текущего меню
    description: Позволяет клиенту увидеть меню
    responses:  
      '200':
        description: Получено меню
        content:
         application/json:
          schema:
           $ref: '#/components/schemas/Menu'
      '400':
          description: Ошибка клиента
      '404':
          description: Информация недоступна
      'default':
          description: Внутренняя ошибка сервера
 /menu/category:
  get:
    tags: [Меню]
    security:
      - bearerAuth: []
    summary: Получения списка блюд в категории
    description: Позволяет клиенту блюда в категории
    responses:  
      '200':
        description: Получен список блюд в категории
        content:
         application/json:
          schema:
           $ref: '#/components/schemas/Category'
      '400':
          description: Ошибка клиента
      '404':
          description: Информация недоступна
      'default':
          description: Внутренняя ошибка сервера
 /dishes/{dishID}}:
  get:
    tags: [Информация о заказах]
    security:
      - bearerAuth: []
    summary: Получение конкретного блюда
    description: Позволяет клиенту получить конкретное блюдо
    operationId: getDishID
    parameters: 
       - name: dishID
         in: path
         required: true
         schema:
          type: string
          format: guid
          example: 123
    responses:  
      '200':
        description: Получено конкретное блюдо
        content:
         application/json:
          schema:
           $ref: '#/components/schemas/DishItems'
      '400':
          description: Ошибка клиента
      '404':
          description: Информация недоступна
      'default':
          description: Внутренняя ошибка сервера
 /order/{orderID}/status:
  get:
    tags: [Статус заказа]
    security:
      - bearerAuth: []
    summary: Получение статуса по заказу
    description: Позволяет пользователю увидеть статус заказа
    operationId: getOrderID
    parameters: 
      - name: orderID
        in: path
        description: Номер заказа
        required: true
        schema:
          type: string
          format: guid
          example: 123
    responses:  
      '200':
        description: Получен статус заказа
        content:
         application/json:
          schema:
           $ref: '#/components/schemas/Status'
      '400':
          description: Ошибка клиента
      '404':
          description: Информация недоступна
      'default':
          description: Внутренняя ошибка сервера
 /users/{userID}/orders:
  get:
    tags: [Информация о заказах]
    security:
      - bearerAuth: []
    summary: Получение истории заказов
    description: Позволяет пользователю увидеть историю заказов
    operationId: getUserID
    parameters: 
       - name: userID
         in: path
         description: Номер пользователя
         required: true
         schema:
          type: string
          format: guid
          example: userId_123
    responses:  
      '200':
        description: Получена история заказов пользователя
        content:
         application/json:
          schema:
           $ref: '#/components/schemas/Orders'
      '400':
          description: Ошибка клиента
      '404':
          description: Информация недоступна
      'default':
          description: Внутренняя ошибка сервера
 /reviews:
  get:
    tags: [Отзывы]
    description: Получить все отзывы пользователя
    responses:
      '200':
        description: Список отзывов
        content:
         application/json:
          schema:
           $ref: '#/components/schemas/Reviews'
      '400':
          description: Ошибка клиента
      '404':
          description: Информация недоступна
      'default':
          description: Внутренняя ошибка сервера
 /orders/{orderID}/reviews:
  post:
    tags: [Отзывы]
    security:
      - bearerAuth: []
    summary: Добавление отзыва о заказе
    description: Позволяет пользователю добавить отзыв о блюде
    operationId: orderID
    parameters: 
      - name: orderID
        in: path
        description: Уникальный идентификатор заказа
        required: true
        schema:
          type: string
          format: guid
          example: 123
    requestBody:
      required: true
      description: Добавлен отзыв о блюде
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Reviews'
    responses:  
      '200':
        description: Блюдо оценено
        content:
         application/json:
          schema:
           type: object
           properties:
            result:
              type: string
              example: Оценка добавлена
              
      '400':
          description: Ошибка клиента
      '404':
          description: Информация недоступна
      'default':
          description: Внутренняя ошибка сервера
 /reviews/{reviewsID}:
  get:
    tags: [Отзывы]
    security:
      - bearerAuth: []
    summary: Получение конкретный отзыв
    description: Позволяет получить отзыв
    operationId: getreviewsID
    parameters: 
       - name: reviewsID
         in: path
         description: Номер отзывы
         required: true
         schema:
          type: string
          format: guid
         example: reviewsId_123
    responses:  
      '200':
        description: Информация об отзыве по заказу
        content:
         application/json:
          schema:
            $ref: '#/components/schemas/Reviews'
      '400':
          description: Ошибка клиента
      '404':
          description: Информация недоступна
      'default':
          description: Внутренняя ошибка сервера
tags:
  - name: Статус заказа
    description: Получение статуса заказа
  - name: Информация о заказах
    description: Получение информации о заказах
  - name: Отзывы
    description: Добавление отзывов
  - name: Меню
    description: Операции связанные с меню
  - name: Пользователи
    description: Операции связанные с пользователями
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Menu:
      type: object
      properties:
        id:
          type: string
          description: Идентификатор 
          example: 123
        category:
          type: string
          description: Категория в меню
          example: Бургеры
    Category:
      type: object
      properties:
        id:
          type: string
          description: Идентификатор 
          example: 123
        dish:
          type: string
          description: Блюдо
          example: Чизбургер
        price:
          type: number
          format: float
          description: Стоимость блюда
          example: 69
    DishItems:
      type: object
      properties:
        id:
          type: string
          description: Идентификатор 
          example: 123
        dish:
          type: string
          description: Блюдо
          example: Чизбургер
        price:
          type: number
          format: float
          description: Стоимость блюда
          example: 69
        description:
          type: string
          description: Описание блюда
          example: Сочный бургер из мраморной говядины
        category:
          type: string
          description: Категория блюда
          example: Бургеры
    Login:
      type: object
      properties:
        login:
          type: string
          description: Логин пользователя
          example: ivanov
        password:
          type: string
          description: Пароль пользователя
          example: 123456
    Register:
      type: object
      properties:
        name:
          type: string
          description: Логин пользователя
          example: ivanov
        password:
          type: string
          description: Пароль пользователя
          example: 123456 
        datebirthday:
          type: string
          format: date
          description: Дата рождения
          example: 01.01.1900
        phonenumber:
          type: string
          description: Номер телефона
          example: 79998887766
    Recovery:
      type: object
      properties:
        phonenumber:
          type: string
          description: Номер телефона
          example: 79998887766
        code:
          type: string
          description: Код
          example: 1234
    Status:
      type: object
      properties:
        status:
          type: string
          enum:
            - Обработка
            - Оформлен
            - Готовится
            - Готов к выдаче
            - Отменен
    Orders:
      type: array
      items:
        type: object
        properties:
          orderID: 
            type: string
            description: Уникальный идентификатор заказа    
          status: 
            enum: 
              - Отменен
              - Выдан
          totalprice:
            type: number  
            description: Итогая стоимость заказа
            example: 100
          orderDate:
            type: string
            format: date-time
            description: Дата и время заказа
          paymentMethod:
            enum: 
            - Наличные
            - Картой
          dishes:
            $ref: '#/components/schemas/OrderDishes' 
                
        
    OrderDishes:
      type: array 
      items:
        type: object
        properties:
          ItemID: 
            type: string
            description: Уникальный идентификатор блюда
            example: 123
          name:
            type: string
            description: Наименование блюда
            example: Бургер
          price:
            type: number
            format: float
            description: Цена заказа
            example: 100
    Reviews:
      type: object
      required:
        - user_id
        - order_id
        - rating
        - review
      properties:
        user_id:
          type: integer
        order_id:
          type: integer
        rating:
          type: number
          enum:
            - 1
            - 2
            - 3
            - 4
            - 5
          description: Рейтинг блюда от пользователя
          example: 5
        review:
          type: string
          description: Отзыв о блюде
          example: Все понравилось
security:
        - bearerAuth: []