name: ci
on:
  push:
    branches:
      - main
      - master
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install mkdocs-mermaid2-plugin
      - run: pip install pillow cairosvg
      - run: pip install beautifulsoup4>=4.11.1
      - run: pip install mkdocs-swagger-ui-tag
      - run: pip3 install mkdocs-build-plantuml-plugin
      - run: pip3 install mkdocs-enumerate-headings-plugin
      - run: pip install mkdocs-glightbox
      - run: mkdocs gh-deploy --force
